CREATE TABLE "COUNTRY" (
    COUNTRY_CODE VARCHAR(3) PRIMARY KEY,
    NAME VARCHAR(60),
    REGION VARCHAR(40),
    INCOME_GROUP VARCHAR(40),
    SPECIAL_NOTES CLOB,

    -- Constraint to ensure COUNTRY_CODE is exactly 3 uppercase letters
    CHECK (COUNTRY_CODE REGEXP '^[A-Z]{3}$')
);

-- Table to store annual population data per country
CREATE TABLE "POPULATION" (
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    DATA_YEAR SMALLINT NOT NULL,
    POPULATION BIGINT NOT NULL,

    PRIMARY KEY (COUNTRY_CODE, DATA_YEAR),

    FOREIGN KEY (COUNTRY_CODE) REFERENCES "COUNTRY"(COUNTRY_CODE)
);

-- Table to store annual GDP (Gross Domestic Product) data per country
CREATE TABLE "GDP" (
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    DATA_YEAR SMALLINT NOT NULL,
    GDP DECIMAL(30, 10) NOT NULL,

    PRIMARY KEY (COUNTRY_CODE, DATA_YEAR),

    FOREIGN KEY (COUNTRY_CODE) REFERENCES "COUNTRY"(COUNTRY_CODE)
);